CREATED_F=keppel_rad.F
LIBNAMES  = $(MAIN_DIRECTORY)$(DEBUG) 
LIBNAMES  +=clasutil fputil recutl bos fpack online_dummy c_bos_io
LIBNAMES  +=lepto63 jetset74 packlib mathlib kernlib lepto63 $(RECSIS_MD_LIBS)
SHARED_LIBS=$(RECSIS_SHARED_LIBS)
include $(CLAS_CMS)/Makefile
